import { AchievementSet, define as $, andNext, orNext } from '@cruncheevos/core'
const set = new AchievementSet({ gameId: 16806, title: 'T-MEK' })

function gameMode(mode) {
  return($(['', 'Mem', '8bit', 0x02ac22, '=', 'Value', '', mode],))
}

function levelComplete(level) {
  return($(
    ['', 'Delta', '8bit', 0x04a6ea, '=', 'Value', '', level],
    ['', 'Mem', '8bit', 0x04a6ea, '=', 'Value', '', level+1],
  ))
}

set.addAchievement({
  title: 'Full-Baked',
  description: 'Defeat Baked on any difficulty and mode.',
  points: 10,
  type: 'progression',
  conditions: {
    core: $(
      ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 0x1],
    ),
    alt1: $(
      orNext(gameMode(0x1), gameMode(0x2)), 
      levelComplete(0x3)
    ),
    alt2: $(
      orNext(gameMode(0x3), gameMode(0x4)), 
      levelComplete(0x4)
    ),
  },
  badge: '579106',
  id: 511858,
})

set.addAchievement({
  title: 'Electrifying',
  description: 'Defeat Shocka on any difficulty and mode.',
  points: 10,
  type: 'progression',
  conditions: {
    core: $(
      ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 0x1],
    ),
    alt1: $(
      gameMode(0x1),
      levelComplete(0x6),
    ),
    alt2: $(
      gameMode(0x2),
      levelComplete(0x7)
    ),
    alt3: $(
      orNext(gameMode(0x3), gameMode(0x4)),
      levelComplete(0x8)
    ),
  },
  badge: '579107',
  id: 511859,
})

set.addAchievement({
  title: 'Multi-Armed Monster',
  description: 'Defeat Venusiva on any difficulty and mode.',
  points: 10,
  type: 'progression',
  conditions: {
    core: $(
      ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 0x1],
    ),
    alt1: $(
      gameMode(0x1),
      levelComplete(0x8),
    ),
    alt2: $(
      gameMode(0x2),
      levelComplete(0xa)
    ),
    alt3: $(
      gameMode(0x3),
      levelComplete(0xc)
    ),
    alt4: $(
      gameMode(0x4),
      levelComplete(0xd)
    ),
  },
  badge: '579108',
  id: 511860,
})

set.addAchievement({
  title: 'Where Is He?',
  description: 'Defeat Phantom on any difficulty and mode.',
  points: 10,
  type: 'progression',
  conditions: {
    core: $(
      ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 0x1],
    ),
    alt1: $(
      gameMode(0x1),
      levelComplete(0x9),
    ),
    alt2: $(
      gameMode(0x2),
      levelComplete(0xb)
    ),
    alt3: $(
      gameMode(0x3),
      levelComplete(0xd)
    ),
    alt4: $(
      gameMode(0x4),
      levelComplete(0xe)
    ),
  },
  badge: '579109',
  id: 511861,
})

set.addAchievement({
  title: 'Boss Master',
  description: `Defeat Brk'oth on any difficulty and mode.`,
  points: 10,
  type: 'progression',
  conditions: {
    core: $(
      ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 0x1],
    ),
    alt1: $(
      gameMode(0x1),
      levelComplete(0xa),
    ),
    alt2: $(
      gameMode(0x2),
      levelComplete(0xc)
    ),
    alt3: $(
      gameMode(0x3),
      levelComplete(0xe)
    ),
    alt4: $(
      gameMode(0x4),
      levelComplete(0xf)
    ),
  },
  badge: '579110',
  id: 511862,
})

set.addAchievement({
  title: 'Champion of the Arena',
  description: 'Defeat Nazrac on any difficulty and mode.',
  points: 25,
  type: 'win_condition',
  conditions: $(
    ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 1],
    ['', 'Mem', '8bit', 0x4a6ea, '=', 'Value', '', 11],
    ['', 'Delta', '8bit', 0x4a6f6, '=', 'Value', '', 0],
    ['', 'Delta', '8bit', 0x4a6fe, '=', 'Value', '', 0],
    ['', 'Mem', '8bit', 0x4a6f6, '=', 'Value', '', 2],
    ['', 'Mem', '8bit', 0x4a6fe, '=', 'Value', '', 1],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 70],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 66],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 90],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 86],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 39],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 84],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 90],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 68],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
  ),
  badge: '579103',
  id: 511855,
})

set.addAchievement({
  title: 'Mek Warrior',
  description: 'Defeat Nazrac on hard difficulty and any mode.',
  points: 50,
  conditions: $(
    ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 1],
    ['', 'Mem', '8bit', 0x2ac0e, '=', 'Value', '', 3],
    ['', 'Mem', '8bit', 0x4a6ea, '=', 'Value', '', 11],
    ['', 'Delta', '8bit', 0x4a6f6, '=', 'Value', '', 0],
    ['', 'Delta', '8bit', 0x4a6fe, '=', 'Value', '', 0],
    ['', 'Mem', '8bit', 0x4a6f6, '=', 'Value', '', 2],
    ['', 'Mem', '8bit', 0x4a6fe, '=', 'Value', '', 1],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 70],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 66],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 90],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 86],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 39],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 84],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 90],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 68],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
  ),
  badge: '579104',
  id: 511856,
})

set.addAchievement({
  title: 'The Long Road',
  description: 'Defeat Nazrac on any difficulty and Arcade+6 mode.',
  points: 100,
  conditions: $(
    ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 1],
    ['', 'Mem', '8bit', 0x2ac22, '=', 'Value', '', 4],
    ['', 'Mem', '8bit', 0x4a6ea, '=', 'Value', '', 17],
    ['', 'Delta', '8bit', 0x4a6f6, '=', 'Value', '', 0],
    ['', 'Delta', '8bit', 0x4a6fe, '=', 'Value', '', 0],
    ['', 'Mem', '8bit', 0x4a6f6, '=', 'Value', '', 2],
    ['', 'Mem', '8bit', 0x4a6fe, '=', 'Value', '', 1],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 70],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 66],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 90],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 86],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 39],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 84],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 90],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 68],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
  ),
  badge: '579105',
  id: 511857,
})

set.addAchievement({
  title: 'Quick Killer',
  description: 'Get 10 kills in less than 60 seconds.',
  points: 5,
  conditions: $(
    ['', 'Mem', '8bit', 0x146, '=', 'Value', '', 1],
    ['OrNext', 'Delta', '16bit', 0x2d338, '=', 'Value', '', 8],
    ['Trigger', 'Delta', '16bit', 0x2d338, '=', 'Value', '', 9],
    ['Trigger', 'Mem', '16bit', 0x2d338, '=', 'Value', '', 10],
    ['AndNext', 'Mem', '8bit', 0x2ac4a, '<=', 'Value', '', 4],
    ['PauseIf', 'Mem', '16bit', 0x1fa20, '=', 'Value', '', 0],
    ['AndNext', 'Mem', '8bit', 0x2ac4a, '=', 'Value', '', 5],
    ['PauseIf', 'Mem', '16bit', 0x1fa20, '<', 'Value', '', 50],
    ['AndNext', 'Mem', '8bit', 0x2ac4a, '=', 'Value', '', 6],
    ['PauseIf', 'Mem', '16bit', 0x1fa20, '<', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 70],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 71],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 66],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 83],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 90],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 78],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 68],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 75],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 86],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 69],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 85],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 73],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 86],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 80],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 84],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 79],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 77],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 66],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 75],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 39],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 84],
    ['PauseIf', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 72],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 78],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 90],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 65],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 67],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 87],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 79],
    ['AndNext', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
    ['AndNext', 'Mem', '8bit', 0x2be02, '=', 'Value', '', 68],
    ['PauseIf', 'Mem', '8bit', 0x2be05, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdfc, '=', 'Value', '', 83],
    ['AndNext', 'Mem', '8bit', 0x2bdff, '=', 'Value', '', 76],
    ['AndNext', 'Mem', '8bit', 0x2bdfe, '=', 'Value', '', 65],
    ['AndNext', 'Mem', '8bit', 0x2be01, '=', 'Value', '', 89],
    ['AndNext', 'Mem', '8bit', 0x2be00, '=', 'Value', '', 69],
    ['PauseIf', 'Mem', '8bit', 0x2be03, '=', 'Value', '', 82],
  ),
  badge: '579112',
  id: 511864,
})

export default set
